const EMPLOYEE_ACTION_TYPES = {
  EMPLOYEE_LIST_REQUEST: 'EMPLOYEE_LIST_REQUEST',
  EMPLOYEE_LIST_FAILURE: 'EMPLOYEE_LIST_FAILURE',
  EMPLOYEE_LIST_SUCCESS: 'EMPLOYEE_LIST_SUCCESS',
};
export default EMPLOYEE_ACTION_TYPES;
