const EVENT_ACTION_TYPES = {
    EVENT_LIST_REQUEST: 'EVENT_LIST_REQUEST',
    EVENT_LIST_FAILURE: 'EVENT_LIST_FAILURE',
    EVENT_LIST_SUCCESS: 'EVENT_LIST_SUCCESS',

    EVENT_DELETE_SUCCESS: 'EVENT_DELETE_SUCCESS',

    EVENT_FORM_LIST_REQUEST: 'EVENT_FORM_LIST_REQUEST',
    EVENT_FORM_LIST_FAILURE: 'EVENT_FORM_LIST_FAILURE',
    EVENT_FORM_LIST_SUCCESS: 'EVENT_FORM_LIST_SUCCESS',

    SQL_EVENT_LIST_SUCCESS: 'SQL_EVENT_LIST_SUCCESS',
    UPDATE_ACTIVE_EVENT_ID: 'UPDATE_ACTIVE_EVENT_ID',

};
export default EVENT_ACTION_TYPES;
