import { StyleSheet } from 'react-native';
import GlobalStyle from '../../style/globalstyle';

export const styles = StyleSheet.create({
  // safeContainer: {flex: 1},
  containerDark: {
    backgroundColor: '#2E2E2E',
    flex: 1,
    paddingTop: 19,
  },
  containerLight: {
    backgroundColor: '#f3f3f3',
    flex: 1,
    paddingTop: 19,
  },
  headText: {
    fontFamily: GlobalStyle.fontSet.RedHatDisplay500,
    fontSize: 12,
    color: '#EAEAEA',
    textAlign: 'center',
    paddingBottom: 10,
  },
  headTextLight: {
    fontFamily: GlobalStyle.fontSet.RedHatDisplay500,
    fontSize: 12,
    color: '#1a1a1a',
    textAlign: 'center',
    paddingBottom: 10,
  },
  leadIdBox: {
    fontFamily: GlobalStyle.fontSet.RedHatDisplay400,
    fontSize: 12,
    color: '#EAEAEA',
    textAlign: 'left',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderColor: '#808191',
    borderRadius: 4,
    borderWidth: 1,
    width: '92%',
    marginHorizontal: 15,
  },
  contactBox: {
    flexDirection: 'row',
    marginTop: 14,
    marginBottom: 5,
    marginLeft: 22,
  },
  buttonLabel: {
    color: '#FBFBFB',
    textTransform: 'capitalize',
    fontFamily: GlobalStyle.fontSet.RedHatDisplay700,
    fontSize: 12,
  },
  contactBtn: {
    backgroundColor: '#30C6EA',
    borderRadius: 3,
  },
  addBtn: {
    height: 35,
    width: 35,
    marginLeft: 8,
    marginTop: 1,
  },
  scanContainer: {
    marginLeft: 16,
    marginBottom: 5,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    width: '90%',
  },
  languageText: {
    fontFamily: GlobalStyle.fontSet.RedHatDisplay700,
    fontSize: 10,
    textAlign: 'center',
    color: '#a3a4a7',
  },
  languageTextActive: {
    fontFamily: GlobalStyle.fontSet.RedHatDisplay700,
    fontSize: 10,
    textAlign: 'center',
    color: '#FBFBFB',
  },
  formLanguageButtonHolder: {
    flexDirection: 'row',
    borderRadius: 3,
    width: '100%',
    alignItems: 'center',
    marginLeft: '25%',
  },
  activeButton: {
    height: 40,
    width: '19%',
    justifyContent: 'center',
    borderRadius: 3,
    backgroundColor: '#30C6EA',
    marginLeft: 10,
    marginBottom: 20,
  },
  inActiveButton: {
    height: 40,
    width: '19%',
    justifyContent: 'center',
    borderRadius: 3,
    borderWidth: 1,
    borderColor: '#4B4D54',
    backgroundColor: '#4B4D54',
    marginLeft: 10,
    marginBottom: 20,
  },
  buttonGroup: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginTop: 25,
    paddingHorizontal: 15,
    marginBottom: 20,
  },
  spaceBtns: {
    flex: 0,
    flexBasis: '48%',
  },
  saveButton: {
    backgroundColor: '#30C6EA',
    borderRadius: 4,
    width: '100%',
    height: 35,
  },
  cancelButton: {
    borderRadius: 4,
    backgroundColor: '#4B4D54',
    width: '100%',
    height: 35,
  },
  actionTitle: {
    color: '#FBFBFB',
    textTransform: 'capitalize',
    fontFamily: GlobalStyle.fontSet.RedHatDisplay700,
    fontSize: 10,
    lineHeight: Platform.OS === 'ios' ? 0 : 15,
  },
  loadingForm: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E2E0E0',
    opacity: 0.8,
    zIndex: 1,
  },
});
